### ISSUE TITLE
小优化，iOS端用户未选择图片时最好判空

### ISSUE THREAD

**Issue by aiyouBug** [xieyezi/flutter-Anniversary#3]
![image](https://user-images.githubusercontent.com/20496772/92711350-0ea63a00-f38b-11ea-9825-d94da5aee311.png)
Future getImage() async {
    pickedFile = await picker.getImage(source: ImageSource.gallery);

    if(pickedFile != null && pickedFile.path.length > 0) { //判空
      setState(() {
        _imageBg = File(pickedFile.path);
        print(pickedFile.path);
      });
    }

**Comment by xieyezi** [comment]
Hi, @aiyouBug 

谢谢提建议，已经优化！！
