### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by afufu** [xieyezi/flutter-Anniversary#4]
呜呜呜好喜欢这个app但是我跑不起来

作者大大有时间能不能联系下我  q q 1499067976  微信  18830970796  或者您发联系方式我联系您 

问题相关： 环境已经配置好  但是显 示 flutter 错误: 程序包androidx.lifecycle不存在 
能帮我看看嘛提前感谢

**Comment by xieyezi** [comment]
@afufu 
我的微信： xieyezi-syc

**Comment by xieyezi** [comment]
> @afufu
> 我的微信： xieyezi-syc

谢谢喜欢
